// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMeta } from "./ColumnMeta";
import type { ResultStats } from "./ResultStats";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Truncated result returned to agents. Full rows stay app-side behind
 * `result_id` (rate-limit + context-bloat protection).
 */
export type AgentResult = { 
/**
 * Key into the app-side result cache (for follow-ups / UI hop-over).
 */
result_id: string, 
/**
 * Ordered output column names.
 */
columns: Array<string>, 
/**
 * Column types, parallel to `columns`.
 */
column_types: Array<ColumnMeta>, 
/**
 * First ≤ 50 rows.
 */
head: Array<{ [key in string]?: JsonValue }>, 
/**
 * Stats (total row count, duration, caps).
 */
stats: ResultStats, 
/**
 * The exact SQL that was executed (agent may cite it; it cannot write it).
 */
sql: string, 
/**
 * Semantic graph version pinned for this execution.
 */
semantic_version: string, };
