// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-agent capability probe result.
 */
export type AgentStatus = { 
/**
 * Agent id.
 */
agent: string, 
/**
 * `claude --version`-style version string, when installed.
 */
version: string | null, 
/**
 * Binary found on PATH.
 */
installed: boolean, 
/**
 * Logged in / authenticated (None = not verified cheaply).
 */
logged_in?: boolean | null, 
/**
 * Human note (e.g. failure reason).
 */
note?: string | null, };
