// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * One streamed agent event (normalized across claude/codex/pi drivers).
 */
export type AgentEvent = { "type": "started", "value": { 
/**
 * Agent id (`claude` / `codex` / `pi` / `byok`).
 */
agent: string, 
/**
 * Driver-native session id, when already known.
 */
session_id: string | null, } } | { "type": "token", "value": { 
/**
 * Text delta.
 */
text: string, } } | { "type": "tool_call", "value": { 
/**
 * Tool name (no `mcp__querora__` prefix).
 */
tool: string, 
/**
 * Tool arguments.
 */
args: JsonValue, } } | { "type": "tool_result", "value": { 
/**
 * Tool name.
 */
tool: string, 
/**
 * Success flag.
 */
ok: boolean, 
/**
 * Short human summary.
 */
summary: string, 
/**
 * Present for `execute_query`: cache key the UI uses to fetch the
 * full result (charts/trust panel) app-side.
 */
result_id?: string | null, } } | { "type": "answer", "value": { 
/**
 * Complete answer.
 */
text: string, } } | { "type": "context_lost", "value": { 
/**
 * Why.
 */
reason: string, } } | { "type": "failed", "value": { 
/**
 * Error description.
 */
error: string, } } | { "type": "done" };
