// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregation operators for metric expressions.
 */
export type AggOp = "sum" | "avg" | "min" | "max" | "count" | "count_distinct" | { "ratio": { 
/**
 * Metric id of the numerator.
 */
numerator: string, 
/**
 * Metric id of the denominator.
 */
denominator: string, } };
