// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DimensionRef } from "./DimensionRef";
import type { Filter } from "./Filter";
import type { MeasureRef } from "./MeasureRef";
import type { OrderSpec } from "./OrderSpec";
import type { SourceId } from "./SourceId";
import type { TimeSpec } from "./TimeSpec";

/**
 * The analytical IR. Agents compose this via tools; the compiler validates
 * it against the published `SemanticGraph` and renders SQL.
 *
 * The `limit` is capped by app config (default 1000) — never trusted.
 */
export type AnalyticalQuery = { 
/**
 * Target source.
 */
source: SourceId, 
/**
 * Metrics to compute.
 */
measures: Array<MeasureRef>, 
/**
 * Dimensions to group by.
 */
dimensions: Array<DimensionRef>, 
/**
 * Filters.
 */
filters: Array<Filter>, 
/**
 * Optional time context.
 */
time?: TimeSpec | null, 
/**
 * Ordering.
 */
order: Array<OrderSpec>, 
/**
 * Requested row limit (server-capped).
 */
limit: number, };
