// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arithmetic operators for metric expression combinations.
 */
export type ArithOp = "add" | "sub" | "mul" | "div";
