// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chart types M0 knows how to render.
 */
export type ChartType = "bar" | "bar_horizontal" | "line" | "area" | "pie" | "table";
