// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ArithOp } from "./ArithOp";
import type { MetricExpr } from "./MetricExpr";

/**
 * Arithmetic combination of two metric sub-expressions.
 */
export type Combination = { 
/**
 * Left operand.
 */
left: MetricExpr, 
/**
 * Operator.
 */
op: ArithOp, 
/**
 * Right operand.
 */
right: MetricExpr, };
