// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Optional period-over-period comparison mode.
 */
export type CompareMode = "previous_period";
