// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How confident Querora is in a suggested graph element.
 */
export type Confidence = "candidate" | "declared";
