// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeGrain } from "./TimeGrain";

/**
 * Reference to a published dimension, optionally at a time grain.
 */
export type DimensionRef = { 
/**
 * Dimension id from the published semantic graph.
 */
dimension_id: string, 
/**
 * Time grain when the dimension is temporal.
 */
grain?: TimeGrain | null, 
/**
 * Output column alias; defaults to the dimension label.
 */
alias?: string | null, };
