// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SemanticDataType } from "./SemanticDataType";

/**
 * A business dimension (a groupable column).
 */
export type Dimension = { 
/**
 * Unique dimension id (referenced by `DimensionRef` / `Filter`).
 */
id: string, 
/**
 * Human label.
 */
label: string, 
/**
 * Entity the dimension lives on.
 */
entity_id: string, 
/**
 * Physical column name.
 */
column: string, 
/**
 * Data type.
 */
data_type: SemanticDataType, 
/**
 * Searchable aliases.
 */
aliases: Array<string>, 
/**
 * Short description surfaced to agents.
 */
description?: string | null, };
