// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An entity: the business name of a table (or view).
 */
export type Entity = { 
/**
 * Unique entity id (slug of the business name).
 */
id: string, 
/**
 * Human label.
 */
label: string, 
/**
 * Physical table name. For virtual entities this is the CTE name
 * (derived from the id) — ignored when `definition_sql` is set.
 */
table: string, 
/**
 * Short description surfaced to agents.
 */
description?: string | null, 
/**
 * Virtual entity: a single SELECT (validated read-only at publish)
 * whose output columns act as this entity's columns. Rendered as a
 * CTE. Authored in the semantic layer (human/AI-published) — agents
 * still never write SQL.
 */
definition_sql?: string | null, };
