// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine-readable error codes for tool failures.
 */
export type ErrorCode = "unauthorized" | "not_found" | "unknown_metric" | "unknown_dimension" | "ambiguous_join" | "invalid_ir" | "source_unavailable" | "not_implemented" | "internal";
