// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A literal filter value. Always parameterized in rendered SQL —
 * user values are never string-interpolated.
 */
export type FilterValue = { "kind": "null" } | { "kind": "bool", "value": boolean } | { "kind": "number", "value": number } | { "kind": "str", "value": string } | { "kind": "list", "value": Array<FilterValue> };
