// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterOp } from "./FilterOp";
import type { FilterValue } from "./FilterValue";

/**
 * A filter on a published dimension.
 */
export type Filter = { 
/**
 * Dimension id from the published semantic graph.
 */
dimension_id: string, 
/**
 * Comparison operator.
 */
op: FilterOp, 
/**
 * Literal(s) to compare against (ignored for `is_null` / `is_not_null`).
 */
value?: FilterValue | null, };
