// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Comparison operators available in filters.
 */
export type FilterOp = "eq" | "not_eq" | "in" | "not_in" | "gt" | "gte" | "lt" | "lte" | "like" | "not_like" | "is_null" | "is_not_null";
