// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Relationship cardinality (M0 models many-to-one from fact to dimension).
 */
export type JoinCardinality = "many_to_one" | "one_to_one";
