// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reference to a published metric, with an optional output alias.
 */
export type MeasureRef = { 
/**
 * Metric id from the published semantic graph.
 */
metric_id: string, 
/**
 * Output column alias; defaults to the metric label.
 */
alias?: string | null, };
