// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MetricExpr } from "./MetricExpr";

/**
 * A business metric.
 */
export type Metric = { 
/**
 * Unique metric id (referenced by `MeasureRef`).
 */
id: string, 
/**
 * Human label.
 */
label: string, 
/**
 * Entity the metric's columns live on.
 */
entity_id: string, 
/**
 * Aggregation expression.
 */
expr: MetricExpr, 
/**
 * Searchable aliases ("revenue", "mrr", …).
 */
aliases: Array<string>, 
/**
 * Short description surfaced to agents.
 */
description?: string | null, };
