// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AggOp } from "./AggOp";
import type { Combination } from "./Combination";

/**
 * The aggregation expression behind a metric. References physical columns
 * of the entity — the agent never sees or writes this; it uses metric ids.
 */
export type MetricExpr = { 
/**
 * Aggregation operator.
 */
op: AggOp, 
/**
 * Column expression (column name; richer SQL expressions post-M0).
 */
column?: string | null, 
/**
 * Human-facing formula, trust-panel only.
 */
human_formula?: string | null, 
/**
 * Arithmetic combination (e.g. margin = (revenue − cost) / revenue).
 * When set, `op`/`column` are ignored. Both sides must aggregate
 * columns of the SAME entity.
 */
combination?: Combination | null, };
