// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OrderDirection } from "./OrderDirection";

/**
 * Ordering on an output column (dimension or measure alias/metric id).
 */
export type OrderSpec = { 
/**
 * Metric id, dimension id, or output alias.
 */
key: string, 
/**
 * Sort direction.
 */
direction: OrderDirection, };
