// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ColumnMeta } from "./ColumnMeta";
import type { ResultStats } from "./ResultStats";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Full query result — served to the UI and the app-side result cache only.
 */
export type QueryResult = { 
/**
 * Cache id; `AgentResult` references it.
 */
result_id: string, 
/**
 * Ordered output column names.
 */
columns: Array<string>, 
/**
 * Column types, parallel to `columns`.
 */
column_types: Array<ColumnMeta>, 
/**
 * All rows (≤ row_cap).
 */
rows: Array<{ [key in string]?: JsonValue }>, 
/**
 * The exact SQL that was executed (trust panel).
 */
sql: string, 
/**
 * Bind parameters used (trust panel; values only, no secrets).
 */
params: Array<JsonValue>, 
/**
 * Semantic graph version pinned for this execution.
 */
semantic_version: string, 
/**
 * Execution stats.
 */
stats: ResultStats, };
