// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Confidence } from "./Confidence";
import type { JoinCardinality } from "./JoinCardinality";
import type { JoinKind } from "./JoinKind";

/**
 * A joinable relationship between two entities.
 */
export type Relationship = { 
/**
 * Unique relationship id (slug).
 */
id: string, 
/**
 * Entity id on the "many" side.
 */
from_entity: string, 
/**
 * Join column on the from side (usually the FK column).
 */
from_column: string, 
/**
 * Entity id on the "one" side.
 */
to_entity: string, 
/**
 * Join column on the to side (usually the PK).
 */
to_column: string, 
/**
 * Cardinality.
 */
cardinality: JoinCardinality, 
/**
 * Where this relationship came from.
 */
confidence: Confidence, 
/**
 * Join rendering: full LEFT JOIN or semi-join (filter-only).
 */
join_kind: JoinKind, };
