// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Execution stats for the trust panel.
 */
export type ResultStats = { 
/**
 * Total rows produced (before head truncation).
 */
row_count: bigint, 
/**
 * Query wall time in milliseconds.
 */
duration_ms: bigint, 
/**
 * Server-side row cap applied to the executed statement.
 */
row_cap: number, 
/**
 * Statement timeout applied, in seconds.
 */
timeout_secs: number, };
