// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Dimension } from "./Dimension";
import type { Entity } from "./Entity";
import type { Metric } from "./Metric";
import type { Relationship } from "./Relationship";
import type { SourceId } from "./SourceId";

/**
 * The whole semantic graph for one source, at one version.
 *
 * `version` is the immutable published version id; queries are pinned to it
 * at execution time so the trust panel can show exactly what was used.
 */
export type SemanticGraph = { 
/**
 * Source this graph describes.
 */
source: SourceId, 
/**
 * Immutable version tag (set on publish; empty in drafts).
 */
version: string, 
/**
 * `true` once a human has published this graph.
 */
published: boolean, 
/**
 * Entities by id.
 */
entities: { [key in string]?: Entity }, 
/**
 * Metrics by id.
 */
metrics: { [key in string]?: Metric }, 
/**
 * Dimensions by id.
 */
dimensions: { [key in string]?: Dimension }, 
/**
 * Relationships (join graph).
 */
relationships: Array<Relationship>, 
/**
 * Sample dimension values for value-aware search (dim id → values).
 * Populated by the EAV pass / curated manually; indexed into FTS.
 */
value_index?: { [key in string]?: Array<string> }, };
