// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Physical/logical data types relevant to analytics.
 */
export type SemanticDataType = "integer" | "number" | "string" | "boolean" | "temporal";
