// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported source kinds (v0: local + remote per locked decision #4).
 */
export type SourceKind = "postgres" | "mysql" | "sqlite" | "duck_db";
