// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceId } from "./SourceId";
import type { SourceKind } from "./SourceKind";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Public description of a connected source. `params` carries only
 * non-secret connection info (host, port, database, file path…).
 */
export type SourceInfo = { id: SourceId, name: string, kind: SourceKind, 
/**
 * Non-secret connection parameters, e.g. `{"host": …, "port": …}`.
 */
params: JsonValue, 
/**
 * ISO-8601 creation timestamp.
 */
created_at: string, };
