// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeUnit } from "./TimeUnit";

/**
 * Time range on a temporal dimension. Relative ranges are resolved at
 * compile time; the resolved absolute bounds are echoed in the ExecutionPlan.
 */
export type TimeRange = { "type": "last", "value": { count: number, unit: TimeUnit, } } | { "type": "between", "value": { start: string, end: string, } };
