// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Time bucketing grains.
 */
export type TimeGrain = "day" | "week" | "month" | "quarter" | "year";
