// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompareMode } from "./CompareMode";
import type { TimeRange } from "./TimeRange";

/**
 * Time context of a query: which temporal dimension anchors it.
 */
export type TimeSpec = { 
/**
 * Temporal dimension id from the published semantic graph.
 */
dimension_id: string, 
/**
 * Range restriction.
 */
range: TimeRange, 
/**
 * When set, ALSO compute the comparison period and return aligned
 * rows tagged `period ∈ {current, previous}`.
 */
compare?: CompareMode | null, };
