// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Units for relative time ranges.
 */
export type TimeUnit = "day" | "week" | "month" | "quarter" | "year";
