// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ErrorCode } from "./ErrorCode";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * A structured tool error. `details` carries corrective hints (e.g. the list
 * of valid metric ids for `unknown_metric`).
 */
export type ToolError = { code: ErrorCode, message: string, details?: JsonValue | null, };
