// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChartType } from "./ChartType";

/**
 * Agent-chosen visualization for a `QueryResult`.
 *
 * `x`/`y` reference result column names; the frontend validates that the
 * columns exist and match the chart type, else falls back to `Table`.
 */
export type VisualizationSpec = { 
/**
 * Chart type.
 */
chart_type: ChartType, 
/**
 * X / category / time column name.
 */
x?: string | null, 
/**
 * Y / value column name.
 */
y?: string | null, 
/**
 * Optional color / split-by column name.
 */
color?: string | null, 
/**
 * Human title for the answer card.
 */
title?: string | null, };
